sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  matrix:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7
    - python: 2.6
      env: DJANGO=1.8
    - python: 3.2
      env: DJANGO=1.4
    - python: 3.3
      env: DJANGO=1.4
    - python: 3.4
      env: DJANGO=1.4
cache:
  directories:
    - $HOME/.cache/pip
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install django~=$DJANGO.0
  - python setup.py install
script: python runtests.py
